# Heart Disease API - Kubernetes Service
# =======================================
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-api-service
  labels:
    app: heart-disease-api
spec:
  type: NodePort
  selector:
    app: heart-disease-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080

